## Perfil per execucions en docker (testing) 

## Port de comunicació
server.port = 8085

## Tasques
tasca.edis=true
cache.enabled=true

advantage.path = //pingu.ames:6262;catalog=//pingu.ames/home/testdbfs/com/comdb.add
advantage.pathmag = //pingu.ames:6262;catalog=//pingu.ames/home/testdbfs/mag/magdb.add

comercial.comandesedi.scheduled=300000
comercial.comandesedi.pdfcheckscheduled=900000

# Enviament email comandes (hi ha un component que no permet enviar emails que no tinguin el domini @ames.group)
# i el substitueix per el de la propietat amb l'adreça.
enviament-email-comandes = true
enviament-email-comandes-adresa = sergi.purcet@ames.group

# Enviament email d'error d'entrades
enviament-email-entrades-error = false

## PostgreSQL (Ames)
ames.datasource.jdbc-url = jdbc:postgresql://dockertest.ames:5432/Ames