## Perfil per execucions en docker (producció)

## Port de comunicació
server.port = 8085 

## Logs (només mostrem els errors)
logging.level.*=INFO
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.hibernate.SQL=INFO

comercial.comandesedi.scheduled=600000
comercial.comandesedi.pdfcheckscheduled=900000

## Tasques
tasca.recalculreserves=true
tasca.actualitzaciopreus=true
tasca.editoalbarans=true
tasca.variacio=true
tasca.entrades=true
tasca.ofs=true
tasca.edis=false
tasca.immobilitzades=true
tasca.ferralla=true
tasca.norecollits=true
cache.enabled=true

## Cues
cua.entrades=q.gp.lliuraments.transferencia

## PostgreSQL (Ames)
ames.datasource.jdbc-url = jdbc:postgresql://webapps.ames:5432/Ames

## Configuració de l'Advantage
advantage.path = //pingu.ames:6262;catalog=//pingu.ames/home/dbfs/com/comdb.add
advantage.pathmag = //pingu.ames:6262;catalog=//pingu.ames/home/dbfs/mag/magdb.add

# Enviament email comandes
enviament-email-comandes = true

# Enviament email d'error d'entrades
enviament-email-entrades-error = true