## Port de comunicació
server.port = 3535

## Application path (tots els enpoints comencen per permisos)
spring.jersey.application-path = permisos

## Evita que s'executi el reload d'Spring dos vegades després de guardar canvis
spring.devtools.restart.poll-interval=3000
spring.devtools.restart.quiet-period=2000

## Màxim tamany del header (per defecte en Jetty 8KB)
server.max-http-header-size = 1MB

## Configuració de l'Advantage (la BBDD testdbfs es copia cada nit amb les dades de producció)
advantage.path = //pingu.ames:6262;catalog=//pingu.ames/home/testdbfs/com/comdb.add
advantage.pathmag = //pingu.ames:6262;catalog=//pingu.ames/home/testdbfs/mag/magdb.add

## Esperem 5 segons a que s'acabin de processar les peticions pendents abans d'apagar el servidor
server.shutdown = graceful
spring.lifecycle.timeout-per-shutdown-phase = 5s

docsapps-folder = /home/docsapps

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

## Log4j
logging.file.name=logs/app.log
logging.file.path=logs
logging.level.ames.permisos=TRACE
logging.level.root=INFO
logging.file.max-size=1MB

## Module configs
### TARIFES ###
comercial.tarifes.xls.numofcolumns=18
### EDI ###
### Planificació de lectura de fitxers EDI de comanda = Cada 30 min
comandesedi.pdfcheck.schedule.enabled=false
comandesedi.process.schedule.enabled=true
## Tasques
tasca.recalculreserves=false
tasca.actualitzaciopreus=false
tasca.editoalbarans=false
tasca.variacio=false
tasca.entrades=false
tasca.ofs=false
tasca.edis=false
tasca.immobilitzades=false
tasca.ferralla=false
tasca.norecollits=false
cache.enabled=false

comercial.comandesedi.scheduled=1800000
### Planificació de comprovacio d'existencia PDF = Cada dia a les 0:00
comercial.comandesedi.pdfcheckscheduled=1800000

## PostgreSQL (Ames)
ames.datasource.jdbc-url = jdbc:postgresql://dockertest.ames:5432/Ames
ames.datasource.username = root
ames.datasource.password = T0rv4lds
ames.datasource.type = com.zaxxer.hikari.HikariDataSource
ames.datasource.driver-class-name = org.postgresql.Driver
ames.datasource.maximum-pool-size = 10
ames.datasource.minimum-idle = 3
ames.datasource.idle-timeout = 300000
ames.datasource.max-lifetime  = 330000
ames.datasource.connection-timeout= 10000

## RabiitMQ (cues)
spring.rabbitmq.host=monitoringsvr.ames
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=_r4bb1tMqS3rv3r_
# Mode transaccional automàtic: Només s'envia ACK quan s'ha fet commit a la BBDD
spring.rabbitmq.listener.simple.acknowledge-mode=AUTO
spring.rabbitmq.listener.simple.transactional=true
# Política de reintents d'entrega del missatge
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=60000
# Permetre que si el missatge falla es reencui i no es perdi evitant
# també l'encuament a una cua de missatges morts (DLQ)
spring.rabbitmq.listener.simple.default-requeue-rejected=true

## Cues de missatges
cua.entrades=q.gp.lliuraments.transferencia.backup

# Correu electrònic
spring.mail.host=mail.ames.es
spring.mail.port=25

# Email al que s'envien els correus an l'entorn de test o en local
enviament-email-adresa-proves = sergi.purcet@ames.group

# Enviament email comandes i adreça on s'envien els emails que no tenen domini @ames.group en entorns
# d'execució que no son producció
enviament-email-comandes = false

# Enviament email d'error d'entrades i adreça on s'envien els emails al fer proves
enviament-email-entrades-error = false