# Configuración para mostrar SQL en múltiples líneas
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat
# El appender utilizado para loguear las consultas
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logLevel=ERROR

# No s'exclou cap categoria (error, info, batch, debug, statement, commit) per a que es mostrin
# les queries dins d'un batch (executeBatch)
excludecategories=info,debug,result,resultset,commit,statement